<a href="https://colab.research.google.com/github/xoro-o/musical-octo-waffle-PyTorch-basic/blob/main/Some_Pytorch_stuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
my_tensor = torch.tensor([[1, 2, 3],[4, 5, 6]],device = device,dtype=torch.float32,requires_grad = True)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [8]:
print(my_tensor.shape)

torch.Size([2, 3])


In [27]:
# Some common initialization methods : 
t = torch.empty((3,3))
print(t)
t = torch.ones((3,3))
print(t)
t = torch.rand((3,3))
t = torch.eye(3,3)
print(t)
t = torch.arange(start=1, end = 10,step = 1)
print(t)
t = torch.linspace(start = 1, end = 10, steps = 20)
t
t = torch.empty(size = (1,5)).uniform_(0,1) # [from,to)
t
t = torch.empty(size = (1,5)).normal_(1,1) # (mean,std)
t
t = torch.diag(torch.ones(3))
t

tensor([[-3.2746e-07,  0.0000e+00,  1.8680e+00],
        [ 1.8864e+00,  6.1925e-01,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [41]:
# initialization and conversion of tensors to other types
tensor = torch.tensor([[1,0,1],[1,1,1]])
tensor.bool()
print(tensor.short().dtype) #int16
tensor.long().dtype #int 64
tensor.float().dtype #float32
tensor.double().dtype #float64

torch.int16


torch.float64

In [45]:
# array to tensor conversions
import numpy as np
np_a = np.zeros((5,6))
t  = torch.from_numpy(np_a)
print(t)
np_a = t.numpy()
np_a

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]])


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [63]:
# Tensor math & Comparison Operations
x = torch.tensor([7,5,4])
y = torch.tensor([3,5,6])

# addition
z1 = torch.empty((3))
torch.add(x,y,out=z1)
z = x + y #type operator overloading
z.shape
# subtraction same for addition
z = torch.true_divide(x,y) #if y is int global broadcasting will take place

# inplace operations
t = torch.zeros(3)
t.add_(x) # operation followed by _ is an inplace optr generally t+=x is inplace , t=t+x is not as said

# exponentiation
z = x.pow(2)
z = x**2

# Simple comparsion
z > 0
z < 0

# matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) # 2x3
x3 = x1.mm(x2)


# matrix exponentiation
mat = torch.rand(5,5) # needs to be square 
print(mat)
mat.matrix_power(2)
mat

# element wise multiply
z = x*y
print(x)
print(y)
z

# dot product
z2 = torch.dot(x,y)
z2
# batch matrix multiplication
batch = 5
m = 10
n = 20
p = 30
t1 = torch.rand((batch,m,n))
t2 = torch.rand((batch,n ,p))
out = torch.bmm(t1,t2) # shape will be (batch,m,p)
out.shape

tensor([[0.9776, 0.8389, 0.6546, 0.7308, 0.0448],
        [0.6820, 0.9200, 0.8000, 0.2399, 0.1179],
        [0.0969, 0.1191, 0.4472, 0.4438, 0.4782],
        [0.8624, 0.5881, 0.7983, 0.7307, 0.9529],
        [0.1207, 0.3774, 0.7712, 0.7556, 0.8308]])
tensor([7, 5, 4])
tensor([3, 5, 6])


torch.Size([5, 10, 30])

In [64]:
# broadcasting 
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
x1 ** x2

tensor([[0.8360, 0.1157, 0.9439, 0.5265, 0.7440],
        [0.7611, 0.0452, 0.9377, 0.2298, 0.9049],
        [0.4619, 0.7090, 0.9963, 0.6345, 0.8014],
        [0.4708, 0.2727, 0.9668, 0.8729, 0.7178],
        [0.2957, 0.8783, 0.9585, 0.8174, 0.6329]])

In [76]:
# other useful tensor operations
sum_x = torch.sum(x,dim=0)
values,indices = torch.max(x,dim=0)   # here in all the suitable following block operations we can use operation like, x.max(dim=_) or say x.min(dim=_)
values,indices = torch.min(x,dim=0)
indices = torch.argmax(x,dim=0) # returns indices
abs_x = torch.abs(x)
z = torch.argmin(x,dim=0)
mean_x = torch.mean(x.float(),dim=0) # needs to be float
z = torch.eq(x,y)
sorted_y, indices = torch.sort(y,dim=0)
z = torch.clamp(x,min=0,max=5)


q = torch.tensor([1,0,1,1,1],dtype=torch.bool)
x3 = torch.all(q)
print(x3)
x3 = torch.any(q)
x3 


tensor(True)


tensor(True)

In [8]:
# Tensor indexing
x = torch.arange(10)
print(x)
ind = [3,5,8]
print(x[ind])

x = torch.rand((3,5))
print(x)
row = torch.tensor([1,0])
col = torch.tensor([2,3])
print(x[row,col])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([3, 5, 8])
tensor([[0.7459, 0.2916, 0.4127, 0.5286, 0.1817],
        [0.1117, 0.3515, 0.4262, 0.5257, 0.5273],
        [0.2461, 0.3854, 0.7650, 0.0565, 0.6414]])
tensor([0.4262, 0.5286])


In [12]:
# advanced indexing
x = torch.arange(10)
print(x[(x<2) | (x>8)]) # | is OR operation
print(x[(x<6) & (x>4)]) 
print(x[x.remainder(2) == 1])

tensor([0, 1, 9])
tensor([5])
tensor([1, 3, 5, 7, 9])


In [18]:
# useful operations 
print(torch.where(x>2,x,x*0)) # torch.where(condition,apply if true,apply if false)
print(torch.tensor([1,1,2,2,4,5,6,8,8]).unique())
print(torch.tensor([[1,2,3],[4,5,6]]).ndimension())
print(torch.tensor([[1,2,3],[4,5,6]]).numel())

tensor([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 4, 5, 6, 8])
2
6


In [22]:
# Tensor Reshaping 

x  = torch.arange(9)
x_3x3 = x.view(3,3)
x_3x3 = x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [21]:
y = x_3x3.t() # transpose
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [26]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
x3 = torch.cat((x1,x2),dim=0)
print(x3.shape)
print(torch.cat((x1,x2),dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [40]:
z = x1.reshape(-1)
print(z.shape)
batch = 64
t = torch.rand((batch,2,5))
z1 = t.reshape((batch,-1))
print(z1.shape)
# now say we want to interchange dimension say, (batch,2,5) to (batch,5,2) so,
# z2 = torch.permute(t,(0,2,1)) or
z2 = t.permute(0,2,1)
print(z2.shape)


# to add new dimension
x = torch.arange(10)
print(x.unsqueeze(1).unsqueeze(1).unsqueeze(0).shape)
print(x.unsqueeze(1).unsqueeze(0).shape)
print(x.unsqueeze(0).shape)

torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10, 1, 1])
torch.Size([1, 10, 1])
torch.Size([1, 10])


In [49]:
# to squeeze : 
z = x.unsqueeze(1).unsqueeze(1).unsqueeze(0)
print(z.squeeze(0).squeeze(1).squeeze(1).shape)

torch.Size([10])
